//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.05 at 05:12:51 PM CEST 
//


package com.ecosense.xml.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schema.klase0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schema.klase0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetObservationResponse }
     * 
     */
    public GetObservationResponse createGetObservationResponse() {
        return new GetObservationResponse();
    }

    /**
     * Create an instance of {@link OMObservation }
     * 
     */
    public OMObservation createOMObservation() {
        return new OMObservation();
    }

    /**
     * Create an instance of {@link GetObservationResponse.ObservationData }
     * 
     */
    public GetObservationResponse.ObservationData createGetObservationResponseObservationData() {
        return new GetObservationResponse.ObservationData();
    }

    /**
     * Create an instance of {@link OMObservation.Type }
     * 
     */
    public OMObservation.Type createOMObservationType() {
        return new OMObservation.Type();
    }

    /**
     * Create an instance of {@link OMObservation.PhenomenonTime }
     * 
     */
    public OMObservation.PhenomenonTime createOMObservationPhenomenonTime() {
        return new OMObservation.PhenomenonTime();
    }

    /**
     * Create an instance of {@link OMObservation.ResultTime }
     * 
     */
    public OMObservation.ResultTime createOMObservationResultTime() {
        return new OMObservation.ResultTime();
    }

    /**
     * Create an instance of {@link OMObservation.Procedure }
     * 
     */
    public OMObservation.Procedure createOMObservationProcedure() {
        return new OMObservation.Procedure();
    }

    /**
     * Create an instance of {@link OMObservation.ObservedProperty }
     * 
     */
    public OMObservation.ObservedProperty createOMObservationObservedProperty() {
        return new OMObservation.ObservedProperty();
    }

    /**
     * Create an instance of {@link OMObservation.FeatureOfInterest }
     * 
     */
    public OMObservation.FeatureOfInterest createOMObservationFeatureOfInterest() {
        return new OMObservation.FeatureOfInterest();
    }

    /**
     * Create an instance of {@link OMObservation.Result }
     * 
     */
    public OMObservation.Result createOMObservationResult() {
        return new OMObservation.Result();
    }

    /**
     * Create an instance of {@link TimeInstant }
     * 
     */
    public TimeInstant createTimeInstant() {
        return new TimeInstant();
    }

}
