//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.06 at 01:17:09 PM CEST 
//


package com.ecosense.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="procedure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="observedProperty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="temporalFilter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.opengis.net/fes/2.0}During"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="featureOfInterest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spatialFilter">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.opengis.net/fes/2.0}BBOX"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="service" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "procedure",
    "observedProperty",
    "temporalFilter",
    "featureOfInterest",
    "spatialFilter"
})
@XmlRootElement(name = "GetObservation", namespace = "http://www.opengis.net/sos/2.0")

public class GetObservation {

    @XmlElement(namespace = "http://www.opengis.net/sos/2.0", required = true)
    protected String procedure;
    @XmlElement(namespace = "http://www.opengis.net/sos/2.0", required = true)
    protected String observedProperty;
    @XmlElement(namespace = "http://www.opengis.net/sos/2.0", required = true)
    protected GetObservation.TemporalFilter temporalFilter;
    @XmlElement(namespace = "http://www.opengis.net/sos/2.0", required = true)
    protected String featureOfInterest;
    @XmlElement(namespace = "http://www.opengis.net/sos/2.0", required = true)
    protected GetObservation.SpatialFilter spatialFilter;
    @XmlAttribute(name = "service", required = true)
    protected String service;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedure(String value) {
        this.procedure = value;
    }

    /**
     * Gets the value of the observedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservedProperty() {
        return observedProperty;
    }

    /**
     * Sets the value of the observedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservedProperty(String value) {
        this.observedProperty = value;
    }

    /**
     * Gets the value of the temporalFilter property.
     * 
     * @return
     *     possible object is
     *     {@link GetObservation.TemporalFilter }
     *     
     */
    public GetObservation.TemporalFilter getTemporalFilter() {
        return temporalFilter;
    }

    /**
     * Sets the value of the temporalFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetObservation.TemporalFilter }
     *     
     */
    public void setTemporalFilter(GetObservation.TemporalFilter value) {
        this.temporalFilter = value;
    }

    /**
     * Gets the value of the featureOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureOfInterest() {
        return featureOfInterest;
    }

    /**
     * Sets the value of the featureOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureOfInterest(String value) {
        this.featureOfInterest = value;
    }

    /**
     * Gets the value of the spatialFilter property.
     * 
     * @return
     *     possible object is
     *     {@link GetObservation.SpatialFilter }
     *     
     */
    public GetObservation.SpatialFilter getSpatialFilter() {
        return spatialFilter;
    }

    /**
     * Sets the value of the spatialFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetObservation.SpatialFilter }
     *     
     */
    public void setSpatialFilter(GetObservation.SpatialFilter value) {
        this.spatialFilter = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.opengis.net/fes/2.0}BBOX"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bbox"
    })
    public static class SpatialFilter {

        @XmlElement(name = "BBOX", required = true)
        protected BBOX bbox;

        /**
         * Gets the value of the bbox property.
         * 
         * @return
         *     possible object is
         *     {@link BBOX }
         *     
         */
        public BBOX getBBOX() {
            return bbox;
        }

        /**
         * Sets the value of the bbox property.
         * 
         * @param value
         *     allowed object is
         *     {@link BBOX }
         *     
         */
        public void setBBOX(BBOX value) {
            this.bbox = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.opengis.net/fes/2.0}During"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "during"
    })
    public static class TemporalFilter {

        @XmlElement(name = "During", required = true)
        protected During during;

        /**
         * Gets the value of the during property.
         * 
         * @return
         *     possible object is
         *     {@link During }
         *     
         */
        public During getDuring() {
            return during;
        }

        /**
         * Sets the value of the during property.
         * 
         * @param value
         *     allowed object is
         *     {@link During }
         *     
         */
        public void setDuring(During value) {
            this.during = value;
        }

    }

}
