//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.06 at 01:17:09 PM CEST 
//


package com.ecosense.xml.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schema.requestklase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schema.requestklase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetObservation }
     * 
     */
    public GetObservation createGetObservation() {
        return new GetObservation();
    }

    /**
     * Create an instance of {@link GetObservation.TemporalFilter }
     * 
     */
    public GetObservation.TemporalFilter createGetObservationTemporalFilter() {
        return new GetObservation.TemporalFilter();
    }

    /**
     * Create an instance of {@link GetObservation.SpatialFilter }
     * 
     */
    public GetObservation.SpatialFilter createGetObservationSpatialFilter() {
        return new GetObservation.SpatialFilter();
    }

    /**
     * Create an instance of {@link BBOX }
     * 
     */
    public BBOX createBBOX() {
        return new BBOX();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link During }
     * 
     */
    public During createDuring() {
        return new During();
    }

    /**
     * Create an instance of {@link TimePeriod }
     * 
     */
    public TimePeriod createTimePeriod() {
        return new TimePeriod();
    }

}
